version: "3.9"
services:
    web:
        image: datprotocol/educative_flask:latest
        restart: always
        command: python /usr/src/app/app.py
        volumes:
          - ./app:/usr/src/app
        ports:
          - "5000:5000"